In this exploratory notebook, I explore both Naive Bayesian and Logistic Regression models and their performance on different tokens. The dataset was so large that, rather than using a built-in cross validation function, I split the dataset manually so the notebook could run without crashing. 

# Raw Counts


In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import regex as re
import numpy as np

from wordcloud import WordCloud, STOPWORDS

from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer as ps
import nltk
!python3 -m nltk.downloader all
nltk.download('punkt')
from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics


from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import Binarizer
from sklearn.metrics import f1_score

/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nlt

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
train_data = pd.read_csv("/content/drive/My Drive/CST4812/Test.csv")
test_data = pd.read_csv("/content/drive/My Drive/CST4812/Train.csv")

In [ ]:
test_data2 = test_data.loc[0:7945]
test_data1 = test_data.loc[7945:15890]
test_data3 = test_data.loc[15890:23835]
test_data4= test_data.loc[23835:29235]
test_data5 = test_data.loc[29235:]

In [ ]:
def clean(data):
  for idx, row in data.iterrows():
    text = re.sub('\n','',row['text'])
    text = re.sub(r'[^a-zA-Z0-9 ]', '', text)
    text = re.sub(r'[0-9]', '', text)
    text = text.lower()
    data.loc[idx, 'text'] = text
clean(train_data)
test_data_list = [test_data1, test_data2, test_data3, test_data4, test_data5]
for x in test_data_list:
  clean(x)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [ ]:
train_data

text  label
0     i always wrote this series off as being a comp...      0
1     st watched    out of dirsteve purcell typical ...      0
2     this movie was so poorly written and directed ...      0
3     the most interesting thing about miryang secre...      1
4     when i first read about berlin am meer i didnt...      0
...                                                 ...    ...
4995  this is the kind of picture john lassiter woul...      1
4996  a must see i saw whipped at a press screening ...      1
4997  nbc should be ashamed i wouldnt allow my child...      0
4998  this movie is a clumsy mishmash of various gho...      0
4999  formula movie about the illegitimate son of a ...      0

[5000 rows x 2 columns]

In [ ]:
vectorizer = CountVectorizer(analyzer='word', max_features= 1200)
trainfeatures = vectorizer.fit_transform(train_data.text)
trainfeatures.toarray()
feature_names = vectorizer.get_feature_names_out()
pd.DataFrame(trainfeatures.toarray(), columns=feature_names)

features1 = vectorizer.transform(test_data1.text).toarray()
features2 = vectorizer.transform(test_data2.text).toarray()
features3 = vectorizer.transform(test_data3.text).toarray()
features4 = vectorizer.transform(test_data4.text).toarray()
features5 = vectorizer.transform(test_data5.text).toarray()

In [ ]:
features1.shape

(7946, 1200)

In [ ]:

from sklearn.model_selection import train_test_split

X = trainfeatures
y = train_data.label


from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression(solver='liblinear')
log_model = log_model.fit(X=X, y=y)
y_pred = log_model.predict(features1)

from sklearn.metrics import accuracy_score
print(accuracy_score(test_data1.label, y_pred))
lgcm = metrics.confusion_matrix(test_data1['label'], y_pred)
print(lgcm)

y_pred2 = log_model.predict(features2)
print(accuracy_score(test_data2.label, y_pred2))
lgcm2 = metrics.confusion_matrix(test_data2['label'], y_pred2)
print(lgcm2)

y_pred3 = log_model.predict(features3)
print(accuracy_score(test_data3.label, y_pred3))
lgcm3 = metrics.confusion_matrix(test_data3['label'], y_pred3)
print(lgcm3)

y_pred4 = log_model.predict(features4)
print(accuracy_score(test_data4.label, y_pred4))
lgcm4 = metrics.confusion_matrix(test_data4['label'], y_pred4)
print(lgcm4)

y_pred5 = log_model.predict(features5)
print(accuracy_score(test_data5.label, y_pred5))
lgcm5 = metrics.confusion_matrix(test_data5['label'], y_pred5)
print(lgcm5)

0.8221746790838158
[[3270  667]
 [ 746 3263]]
0.8173923986911653
[[3295  744]
 [ 707 3200]]
0.8064434935816763
[[3203  801]
 [ 737 3205]]
0.8050361044251064
[[2174  498]
 [ 555 2174]]
0.8133766836971668
[[4381  990]
 [1019 4375]]


In [ ]:

from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(trainfeatures, train_data['label'])
nb_pred = clf.predict(features1)
print(accuracy_score(test_data1.label, nb_pred))
lgcm = metrics.confusion_matrix(test_data1['label'], nb_pred)
print(lgcm)

nb_pred2 = clf.predict(features2)
print(accuracy_score(test_data2.label, nb_pred2))
lgcm2 = metrics.confusion_matrix(test_data1['label'], nb_pred2)
print(lgcm2)

nb_pred3 = clf.predict(features3)
print(accuracy_score(test_data3.label, nb_pred3))
lgcm3 = metrics.confusion_matrix(test_data3['label'], nb_pred3)
print(lgcm3)


nb_pred4 = clf.predict(features4)
print(accuracy_score(test_data4.label, nb_pred4))
lgcm4 = metrics.confusion_matrix(test_data4['label'], nb_pred4)
print(lgcm4)

nb_pred5 = clf.predict(features5)
print(accuracy_score(test_data5.label, nb_pred5))
lgcm5 = metrics.confusion_matrix(test_data5['label'], nb_pred5)
print(lgcm5)

0.8100931286181726
[[3262  675]
 [ 834 3175]]
0.8127359677825321
[[2042 1895]
 [2109 1900]]
0.8095897306821042
[[3310  694]
 [ 819 3123]]
0.8091094241807073
[[2223  449]
 [ 582 2147]]
0.8080817464003716
[[4438  933]
 [1133 4261]]


#Unigrams without stop and rare words

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords = stopwords.words("english")
porter = ps()

def clean2(data):
  for idx, row in data.iterrows():
    text = row['text']
    text = ' '.join([ele for ele in text.split() if ele not in stopwords])
    data.loc[idx, 'text'] = text

    
clean2(train_data)
for x in test_data_list:
  clean2(x)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [ ]:
train_data

text  label
0     always wrote series complete stinkfest jim bel...      0
1     st watched dirsteve purcell typical mary kate ...      0
2     movie poorly written directed fell asleep minu...      0
3     interesting thing miryang secret sunshine acto...      1
4     first read berlin meer didnt expect much thoug...      0
...                                                 ...    ...
4995  kind picture john lassiter would making today ...      1
4996  must see saw whipped press screening hilarious...      1
4997  nbc ashamed wouldnt allow children see definit...      0
4998  movie clumsy mishmash various ghoststory suspe...      0
4999  formula movie illegitimate son rich chilenian ...      0

[5000 rows x 2 columns]

In [ ]:
vectorizer = CountVectorizer(
    analyzer = 'word',
    lowercase = False,
    min_df = 3)
trainfeatures = vectorizer.fit_transform(train_data.text).toarray()


features1 = vectorizer.transform(test_data1.text).toarray()
features2 = vectorizer.transform(test_data2.text).toarray()
features3 = vectorizer.transform(test_data3.text).toarray()
features4 = vectorizer.transform(test_data4.text).toarray()
features5 = vectorizer.transform(test_data5.text).toarray()

In [ ]:
from sklearn.model_selection import train_test_split

X = trainfeatures
y = train_data.label


from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression(solver='liblinear')
log_model = log_model.fit(X=X, y=y)
y_pred = log_model.predict(features1)

from sklearn.metrics import accuracy_score
print(accuracy_score(test_data1.label, y_pred))
lgcm1 = metrics.confusion_matrix(test_data1['label'], y_pred)
print(lgcm1)

y_pred2 = log_model.predict(features2)
print(accuracy_score(test_data2.label, y_pred2))
lgcm2 = metrics.confusion_matrix(test_data2['label'], y_pred2)
print(lgcm2)

y_pred3 = log_model.predict(features3)
print(accuracy_score(test_data3.label, y_pred3))
lgcm3 = metrics.confusion_matrix(test_data3['label'], y_pred3)
print(lgcm3)

y_pred4 = log_model.predict(features4)
print(accuracy_score(test_data4.label, y_pred4))
lgcm4 = metrics.confusion_matrix(test_data4['label'], y_pred4)
print(lgcm4)

y_pred5 = log_model.predict(features5)
print(accuracy_score(test_data5.label, y_pred5))
lgcm5 = metrics.confusion_matrix(test_data5['label'], y_pred5)
print(lgcm5)

0.8557764913163856
[[3350  587]
 [ 559 3450]]
0.8472187264032217
[[3381  658]
 [ 556 3351]]
0.8480996727913416
[[3345  659]
 [ 548 3394]]
0.8431771894093686
[[2241  431]
 [ 416 2313]]
0.844217371110079
[[4493  878]
 [ 799 4595]]


In [ ]:
clf = MultinomialNB()
clf.fit(trainfeatures, train_data['label'])
nb_pred = clf.predict(features1)
print(accuracy_score(test_data1.label, nb_pred))
lgcm = metrics.confusion_matrix(test_data1['label'], nb_pred)
print(lgcm)

nb_pred2 = clf.predict(features2)
print(accuracy_score(test_data2.label, nb_pred2))
lgcm2 = metrics.confusion_matrix(test_data1['label'], nb_pred2)
print(lgcm2)

nb_pred3 = clf.predict(features3)
print(accuracy_score(test_data3.label, nb_pred3))
lgcm3 = metrics.confusion_matrix(test_data3['label'], nb_pred3)
print(lgcm3)


nb_pred4 = clf.predict(features4)
print(accuracy_score(test_data4.label, nb_pred4))
lgcm4 = metrics.confusion_matrix(test_data4['label'], nb_pred4)
print(lgcm4)

nb_pred5 = clf.predict(features5)
print(accuracy_score(test_data5.label, nb_pred5))
lgcm5 = metrics.confusion_matrix(test_data5['label'], nb_pred5)
print(lgcm5)

0.8347596274855273
[[3440  497]
 [ 816 3193]]
0.8335011326453562
[[2095 1842]
 [2181 1828]]
0.8306065945129625
[[3432  572]
 [ 774 3168]]
0.8361414552860581
[[2319  353]
 [ 532 2197]]
0.8329772410589874
[[4654  717]
 [1081 4313]]


# tf-idf Vectors

In [ ]:
tfIdf = TfidfVectorizer(min_df = 3)
trainfeatures = tfIdf.fit_transform(train_data.text)
trainfeatures.toarray()
feature_names = tfIdf.get_feature_names_out()
pd.DataFrame(trainfeatures.toarray(), columns=feature_names)

features1 = tfIdf.transform(test_data1.text).toarray()
features2 = tfIdf.transform(test_data2.text).toarray()
features3 = tfIdf.transform(test_data3.text).toarray()
features4 = tfIdf.transform(test_data4.text).toarray()
features5 = tfIdf.transform(test_data5.text).toarray()

In [ ]:
X = trainfeatures
y = train_data.label

log_model = LogisticRegression(solver='liblinear')
log_model = log_model.fit(X=X, y=y)
y_pred = log_model.predict(features1)

print(accuracy_score(test_data1['label'], y_pred))
lgcm = metrics.confusion_matrix(test_data1['label'], y_pred)
print(lgcm)

y_pred2 = log_model.predict(features2)
print(accuracy_score(test_data2.label, y_pred2))
lgcm2 = metrics.confusion_matrix(test_data2['label'], y_pred2)
print(lgcm2)

y_pred3 = log_model.predict(features3)
print(accuracy_score(test_data3.label, y_pred3))
lgcm3 = metrics.confusion_matrix(test_data3['label'], y_pred3)
print(lgcm3)

y_pred4 = log_model.predict(features4)
print(accuracy_score(test_data4.label, y_pred4))
lgcm4 = metrics.confusion_matrix(test_data4['label'], y_pred4)
print(lgcm4)

y_pred5 = log_model.predict(features5)
print(accuracy_score(test_data5.label, y_pred5))
lgcm5 = metrics.confusion_matrix(test_data5['label'], y_pred5)
print(lgcm5)

0.8608104706770702
[[3340  597]
 [ 509 3500]]
0.8618172665492071
[[3411  628]
 [ 470 3437]]
0.8625723634533098
[[3387  617]
 [ 475 3467]]
0.8598407702277356
[[2253  419]
 [ 338 2391]]
0.8594519275429633
[[4545  826]
 [ 687 4707]]


In [ ]:
print(y_pred5[1:10])
print(test_data5.head(10))

[1 1 1 0 0 0 0 1 0]
                                                    text  label
29235  comedy version strangers train works pretty we...      0
29236  hands ripper br br aspect ratio br br sound fo...      0
29237  clocking five seasons small screen george mild...      1
29238  new york one hot night four famous iconic figu...      1
29239  didnt know expect started watching movie end p...      0
29240  previous reviewer said movie bad movie glorifi...      0
29241  give movie one truly awful movie sound track d...      0
29242  dont know begin movie feels lot like one cheap...      0
29243  whenever people ask name scariest movie ive ev...      1
29244  ostensibly zgrade dtv horror filmbr br lines l...      0


In [ ]:
print(test_data5.loc[29235]['text'])
print(test_data5.loc[29236]['text'])

comedy version strangers train works pretty well harsh grader rating reflects mostly characters plot performances extremely good course two stars devito crystal shine performer acts well enough play comedy works level short slapstick devito characters work best depraved character portrayed writing hack would probably real published lauded much hacks character would real life great agent multiple solicitations characters one dimensional okay comedy crystalss character written well desire kill moma sudden makes sense looks like pitiful attempt humor pitiful attempts often movie flows fairly well
hands ripper br br aspect ratio br br sound format monobr br edwardian doctor eric porter uses newfangled freudian analysis young girl angharad rees turns daughter jack ripper deadlybr br unlikely hammer horror respectable society figure takes charge beautiful young waif without attracting much whiff scandal even takes murdering sundry variety lethal implements broken mirrors hatpins etc lw david

In [ ]:
clf = MultinomialNB()
clf.fit(trainfeatures, train_data['label'])
nb_pred = clf.predict(features1)
print(accuracy_score(test_data1.label, nb_pred))
lgcm = metrics.confusion_matrix(test_data1['label'], nb_pred)
print(lgcm)

nb_pred2 = clf.predict(features2)
print(accuracy_score(test_data2.label, nb_pred2))
lgcm2 = metrics.confusion_matrix(test_data1['label'], nb_pred2)
print(lgcm2)

nb_pred3 = clf.predict(features3)
print(accuracy_score(test_data3.label, nb_pred3))
lgcm3 = metrics.confusion_matrix(test_data3['label'], nb_pred3)
print(lgcm3)


nb_pred4 = clf.predict(features4)
print(accuracy_score(test_data4.label, nb_pred4))
lgcm4 = metrics.confusion_matrix(test_data4['label'], nb_pred4)
print(lgcm4)

nb_pred5 = clf.predict(features5)
print(accuracy_score(test_data5.label, nb_pred5))
lgcm5 = metrics.confusion_matrix(test_data5['label'], nb_pred5)
print(lgcm5)

0.8504908129876667
[[3507  430]
 [ 758 3251]]
0.8449534356909136
[[2111 1826]
 [2212 1797]]
0.8423105965265543
[[3505  499]
 [ 754 3188]]
0.8472505091649695
[[2360  312]
 [ 513 2216]]
0.843381328379006
[[4736  635]
 [1051 4343]]


# Binary Features

In [ ]:
vectorizer = CountVectorizer(
    ngram_range = (2,2),
    lowercase = False,
    min_df = 3)


features1 = vectorizer.transform(test_data1.text).toarray()
features2 = vectorizer.transform(test_data2.text).toarray()
features3 = vectorizer.transform(test_data3.text).toarray()
features4 = vectorizer.transform(test_data4.text).toarray()
features5 = vectorizer.transform(test_data5.text).toarray()

In [ ]:
features1.shape

(7946, 21029)

In [ ]:
X = trainfeatures
y = train_data.label


from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression(solver='liblinear')
log_model = log_model.fit(X=X, y=y)
y_pred = log_model.predict(features1)

from sklearn.metrics import accuracy_score
print(accuracy_score(test_data1['label'], y_pred))
lgcm = metrics.confusion_matrix(test_data1['label'], y_pred)
print(lgcm)

y_pred2 = log_model.predict(features2)
print(accuracy_score(test_data2.label, y_pred2))
lgcm2 = metrics.confusion_matrix(test_data2['label'], y_pred2)
print(lgcm2)

y_pred3 = log_model.predict(features3)
print(accuracy_score(test_data3.label, y_pred3))
lgcm3 = metrics.confusion_matrix(test_data3['label'], y_pred3)
print(lgcm3)

y_pred4 = log_model.predict(features4)
print(accuracy_score(test_data4.label, y_pred4))
lgcm4 = metrics.confusion_matrix(test_data4['label'], y_pred4)
print(lgcm4)

y_pred5 = log_model.predict(features5)
print(accuracy_score(test_data5.label, y_pred5))
lgcm5 = metrics.confusion_matrix(test_data5['label'], y_pred5)

0.7778756607097911
[[2960  977]
 [ 788 3221]]
0.7764913163856029
[[3015 1024]
 [ 752 3155]]
0.7796375534860307
[[2976 1028]
 [ 723 3219]]
0.7724495463803
[[2005  667]
 [ 562 2167]]
0.783743613562471


In [ ]:
clf = MultinomialNB()
clf.fit(trainfeatures, train_data['label'])
nb_pred = clf.predict(features1)
print(accuracy_score(test_data1.label, nb_pred))
lgcm = metrics.confusion_matrix(test_data1['label'], nb_pred)
f1 = f1_score(test_data1['label'], nb_pred, average=None)
print(lgcm)
print("F1 Score: ")
print(f1)

nb_pred2 = clf.predict(features2)
print(accuracy_score(test_data2.label, nb_pred2))
lgcm2 = metrics.confusion_matrix(test_data1['label'], nb_pred2)
print(lgcm2)

nb_pred3 = clf.predict(features3)
print(accuracy_score(test_data3.label, nb_pred3))
lgcm3 = metrics.confusion_matrix(test_data3['label'], nb_pred3)
print(lgcm3)


nb_pred4 = clf.predict(features4)
print(accuracy_score(test_data4.label, nb_pred4))
lgcm4 = metrics.confusion_matrix(test_data4['label'], nb_pred4)
print(lgcm4)

nb_pred5 = clf.predict(features5)
print(accuracy_score(test_data5.label, nb_pred5))
lgcm5 = metrics.confusion_matrix(test_data5['label'], nb_pred5)
print(lgcm5)

#Conclusion


1. The model that worked best for me was the linear regression model of the tf-idf vectors. I believe this worked well as it accounts for differences in length, and I cleaned it the same as the unigrams without stop or rare words. I played around with percentages and raw count values for the minimum document frequeny, but settling on 3 gave me the best scores across the board. The frequencies performed better than raw counts. 

2. These reviews (after stop and rare word removal) were incorrectly classified as positive  in my if-idf logistic regression model. I have bolded the words that I believe caused my model a problem, leading to the misclassification.

1. comedy version strangers train **works pretty well** harsh grader rating reflects mostly characters plot performances **extremely good** course two stars devito crystal **shine** performer acts well enough play comedy works level short slapstick devito characters work best depraved character portrayed writing hack would probably real published lauded much hacks character would real life great agent multiple solicitations characters one dimensional okay comedy crystalss character **written well** desire kill moma sudden makes sense looks like pitiful attempt humor pitiful attempts often** movie flows fairly well**


2. hands ripper br br aspect ratio br br sound format monobr br edwardian doctor eric porter uses newfangled freudian analysis young girl angharad rees turns daughter jack ripper deadlybr br unlikely hammer horror **respectable** society figure takes charge **beautiful** young waif without **attracting** much whiff scandal even takes murdering sundry variety lethal implements broken mirrors hatpins etc lw davidsons screenplay wanders aimlessly one murder another sacrificing materials inherent subtext porters obvious **attraction** rees **favor** commercial melodrama tone remains subdued throughout gore scenes **surprisingly vivid** even hammer clipped original us release despite r rating mpaa though complete version available home video porter rees give **excellent** performances climax st pauls cathedral definite** highlight** rest film strangely hollow unaffecting directed peter sasdy